services:
  - type: web
    name: telegram-mtproxy
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET
        value: your_32char_secret_here
      - key: TAG
        value: e2b4f7d91a3c4e79a6b0e8d43f5a278b
      - key: MTP_PORT
        value: "10000"
